### ISSUE TITLE
Persist Provider data in IPFS

### ISSUE THREAD

**Issue by alvaro-alonso** [taia-x/taia-x#43]
**Background:**
A provider has collected over time a variety of datasets for different driving scenarios and car types. To offer this dataset on the marketplace it needs to comply with prevailing ontology standards. After finding a suitable ontology for the generated data, the provider transforms the data to match the selected ontology.

- [x] Define example Ontology for Advanced Driver Assistance Systems (ADAS)
- [x] Implement IPFS communication via Frontend to get CID
- [x] Update documentation

**Comment by kaustabhbarman** [comment]
I am holding off this ticket since we have to discuss about how we want to upload the data to IPFS. The current options are:
1. Uploading through marketplace. Then we will need to implement front-end first to support uploading of data through a web-page.
2. If we want to keep the data upload separate from the marketplace, then we can push it directly to IPFS from our python scripts.

**Comment by repype** [comment]
Documentation of js-ipfs files api: https://github.com/ipfs/js-ipfs/blob/master/docs/core-api/FILES.md
