### ISSUE TITLE
Examine Storage Datatypes in Smart Contract

### ISSUE THREAD

**Issue by amrap030** [taia-x/taia-x#73]
### Context

As I was working on the integration of the `Role based Access` Smart Contract to the frontend, I discovered the following. When I wanted to fetch the storage of the Smart Contract via the [Taquito](https://github.com/ecadlabs/taquito) Library, I got the following response:

<img width="1014" alt="Bildschirmfoto 2021-11-25 um 03 28 19" src="https://user-images.githubusercontent.com/35061229/143367191-b2688b45-edd4-49f2-b4aa-57d32d0085eb.png">

This result is essentially a map, that contains the id of the `big_map` storage in the contract, which you can see in the following image:

<img width="792" alt="Bildschirmfoto 2021-11-25 um 03 32 13" src="https://user-images.githubusercontent.com/35061229/143367535-15e11e7d-d3d7-4589-aa2b-63f38984b871.png">

However, this response is useless, if you want to get the entire contract storage. The library doesn't provide a method to iterate over the `big_map` items. The only way to get an item of the `big_map` is to fetch a specific item by a key with `await storage.get("tz1den1niGxC9xHXZGdMfbGmXjmMzK2HsDQs")` for example. However, if you would like to get all mappings in `big_map`, this would require to know all keys beforehand. Interestingly, with normal `MichelsonMap` datatype, the library provides a method to iterate over all keys and values, as described in [this Article](https://medium.com/coinmonks/working-with-michelson-maps-in-taquito-8d8be9930662). It seems that the developers of the Taquito library may work on this at some time, based on these issues [222](https://github.com/ecadlabs/taquito/issues/222) and [398](https://github.com/ecadlabs/taquito/issues/398).

It seems, that the only way to get meaningfull data from a contract storage is to use a public API, for example https://tzstats.com/docs/api#tezos-api. With this API, it is possible to query all the values of our contract by fetching `https://api.granada.tzstats.com/explorer/bigmap/149408/values`, by passing the `big_map` id, with the following response:

<img width="685" alt="Bildschirmfoto 2021-11-25 um 03 41 10" src="https://user-images.githubusercontent.com/35061229/143370597-7ab533d2-c39c-4567-a2a1-ab0833e9923e.png">

While this response is a lot more useful than the response of the library, it is still not what I would expect, to work on the frontend with. The good thing is, that I get all the addresses in the storage and also the role. However, the format of the role is very strange.

```js
[
...
    {
        "key": "tz1gqFmpMK4SHwWhTGBUr3t3HKXuyy22QND7", // fine for me
        "key_hash": "expruLuvA3GGvTi4af7JXpMRVhwAmCiGX4N85kchJg7fjPg4NxVUUi",
        "value": {
            "@or_0": { // what is this strange structure?
                "customer": null // why is customer null?
            }
        }
    },
...
]
```

This structure also reflects, when I use a Block explorer in the Browser, by showing this strange `or value{ "customer": {} }`:

<img width="892" alt="Bildschirmfoto 2021-11-25 um 03 47 45" src="https://user-images.githubusercontent.com/35061229/143371141-4cb67587-2b10-4e97-8411-7f760ac382ee.png">

### Suggestion

What I would like to receive in the frontend is a structure as follows:

```js
[
...
    {
        "key": "tz1gqFmpMK4SHwWhTGBUr3t3HKXuyy22QND7",
        "key_hash": "expruLuvA3GGvTi4af7JXpMRVhwAmCiGX4N85kchJg7fjPg4NxVUUi",
        "role": "customer"
    },
...
]
```

Also, I would continue to use `big_map` as datatype, as this type is meant for a lot of data and is most efficient in terms of gas costs.

- [ ] examine the storage datatypes in a smart contract, especially `big_map` and try to adjust the current `Role based Access` smart contract to save and return a more useful data structure

**Comment by repype** [comment]
I did some research and found [this]() Repository. It introduces some concepts which could be helpful for our project and perhaps also for the frontend so I wanted to share it :)
For the problem you describe, there is also a solution in it: A collection of NFTs needs to be fetched in the frontend. Therefore, a data structure `tokenIds` is requested, which then returns a `Set<nat>` ([frontend](https://github.com/octo-technology/Tezos-Land-FA2-NFT-Boilerplate/blob/main/src/frontend/src/pages/Map/Map.controller.tsx#L56-L60) and [smart contract datatype](https://github.com/octo-technology/Tezos-Land-FA2-NFT-Boilerplate/blob/47d6f995f36e92cf966f80dec658e8b1cb2e08b8/src/contracts/src/domain_storage/storage_definition.mligo#L14)).

![image](https://user-images.githubusercontent.com/49333505/144754648-931c74c6-e003-4c4f-be7b-15d6dc6f8034.png)

Further details about the tokenIds are then fetched by direct calls to the getter of the bigmap by iterating over the set ([see here](https://github.com/octo-technology/Tezos-Land-FA2-NFT-Boilerplate/blob/main/src/frontend/src/pages/Map/Map.controller.tsx#L61-L78)). 

![image](https://user-images.githubusercontent.com/49333505/144754675-aac5aca2-ea9c-4049-b1cb-debbccd14462.png)

This approach is somewhat similar to use cases in Ethereum. To achieve this we need to introduce a bigmap<T> and in addition a set<nat>, which both get updated upon creation of new instances - as [here](https://github.com/octo-technology/Tezos-Land-FA2-NFT-Boilerplate/blob/47d6f995f36e92cf966f80dec658e8b1cb2e08b8/src/contracts/src/entrypoints/land_entrypoints/mint.mligo#L27-L28). 

![image](https://user-images.githubusercontent.com/49333505/144754725-039dbb7a-cff6-4c4c-9e9d-0a32ffe8d557.png)

For listing of the sensor data I understand the need, but - just to be sure - I wanted to ask if we really need to fetch the collections for users as well (It's not a problem, I just wanted to ask if this is a required feature before we make the adjustments because set entries are unique which might cause some pitfalls for this particular use case))? 
Furthermore, I am aware that this method could be very slow with large data sets. But in this case a paging mechanism could provide a workaround, or what do you think @amrap030?
> [LIGO Set documentation](https://ligolang.org/docs/language-basics/sets-lists-tuples#sets)

**Comment by amrap030** [comment]
Hey @repype, thank you for this detailed research. I know the workaround by getting items from a set via a unique key. You are also right, this would not be feasible when querying the entire contents of the storage at once, but we can implement some paging, searching and filtering functionality in the frontend. For now, I don't think we need this for the role contract. We only require this, if we want to display roles of an address in our frontend application. This task was more intended to clarify the structure, and if there are possibilities to enhance this, to prevent pitfalls in future contract implementations, where we definitely need information in the frontend. We will definitely need this for the NFT's.
